// Code generated by protoc-gen-go. DO NOT EDIT.
// source: knn.proto

package knnpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vector struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Points               []float32 `protobuf:"fixed32,2,rep,packed,name=points,proto3" json:"points,omitempty"`
	Namespace            string    `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{0}
}

func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (m *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(m, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vector) GetPoints() []float32 {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Vector) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type CreateSingleVectorRequest struct {
	Vector               *Vector  `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSingleVectorRequest) Reset()         { *m = CreateSingleVectorRequest{} }
func (m *CreateSingleVectorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSingleVectorRequest) ProtoMessage()    {}
func (*CreateSingleVectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{1}
}

func (m *CreateSingleVectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSingleVectorRequest.Unmarshal(m, b)
}
func (m *CreateSingleVectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSingleVectorRequest.Marshal(b, m, deterministic)
}
func (m *CreateSingleVectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSingleVectorRequest.Merge(m, src)
}
func (m *CreateSingleVectorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSingleVectorRequest.Size(m)
}
func (m *CreateSingleVectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSingleVectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSingleVectorRequest proto.InternalMessageInfo

func (m *CreateSingleVectorRequest) GetVector() *Vector {
	if m != nil {
		return m.Vector
	}
	return nil
}

type CreateSingleVectorResponse struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSingleVectorResponse) Reset()         { *m = CreateSingleVectorResponse{} }
func (m *CreateSingleVectorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSingleVectorResponse) ProtoMessage()    {}
func (*CreateSingleVectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{2}
}

func (m *CreateSingleVectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSingleVectorResponse.Unmarshal(m, b)
}
func (m *CreateSingleVectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSingleVectorResponse.Marshal(b, m, deterministic)
}
func (m *CreateSingleVectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSingleVectorResponse.Merge(m, src)
}
func (m *CreateSingleVectorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSingleVectorResponse.Size(m)
}
func (m *CreateSingleVectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSingleVectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSingleVectorResponse proto.InternalMessageInfo

func (m *CreateSingleVectorResponse) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CreateMultipleVectorRequest struct {
	Vectors              []*Vector `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateMultipleVectorRequest) Reset()         { *m = CreateMultipleVectorRequest{} }
func (m *CreateMultipleVectorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMultipleVectorRequest) ProtoMessage()    {}
func (*CreateMultipleVectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{3}
}

func (m *CreateMultipleVectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMultipleVectorRequest.Unmarshal(m, b)
}
func (m *CreateMultipleVectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMultipleVectorRequest.Marshal(b, m, deterministic)
}
func (m *CreateMultipleVectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMultipleVectorRequest.Merge(m, src)
}
func (m *CreateMultipleVectorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMultipleVectorRequest.Size(m)
}
func (m *CreateMultipleVectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMultipleVectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMultipleVectorRequest proto.InternalMessageInfo

func (m *CreateMultipleVectorRequest) GetVectors() []*Vector {
	if m != nil {
		return m.Vectors
	}
	return nil
}

type CreateMultipleVectorResponse struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMultipleVectorResponse) Reset()         { *m = CreateMultipleVectorResponse{} }
func (m *CreateMultipleVectorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMultipleVectorResponse) ProtoMessage()    {}
func (*CreateMultipleVectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{4}
}

func (m *CreateMultipleVectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMultipleVectorResponse.Unmarshal(m, b)
}
func (m *CreateMultipleVectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMultipleVectorResponse.Marshal(b, m, deterministic)
}
func (m *CreateMultipleVectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMultipleVectorResponse.Merge(m, src)
}
func (m *CreateMultipleVectorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMultipleVectorResponse.Size(m)
}
func (m *CreateMultipleVectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMultipleVectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMultipleVectorResponse proto.InternalMessageInfo

func (m *CreateMultipleVectorResponse) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CreateStreamVectorRequest struct {
	Vectors              []*Vector `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateStreamVectorRequest) Reset()         { *m = CreateStreamVectorRequest{} }
func (m *CreateStreamVectorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStreamVectorRequest) ProtoMessage()    {}
func (*CreateStreamVectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{5}
}

func (m *CreateStreamVectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStreamVectorRequest.Unmarshal(m, b)
}
func (m *CreateStreamVectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStreamVectorRequest.Marshal(b, m, deterministic)
}
func (m *CreateStreamVectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStreamVectorRequest.Merge(m, src)
}
func (m *CreateStreamVectorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStreamVectorRequest.Size(m)
}
func (m *CreateStreamVectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStreamVectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStreamVectorRequest proto.InternalMessageInfo

func (m *CreateStreamVectorRequest) GetVectors() []*Vector {
	if m != nil {
		return m.Vectors
	}
	return nil
}

type CreateStreamVectorResponse struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStreamVectorResponse) Reset()         { *m = CreateStreamVectorResponse{} }
func (m *CreateStreamVectorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStreamVectorResponse) ProtoMessage()    {}
func (*CreateStreamVectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{6}
}

func (m *CreateStreamVectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStreamVectorResponse.Unmarshal(m, b)
}
func (m *CreateStreamVectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStreamVectorResponse.Marshal(b, m, deterministic)
}
func (m *CreateStreamVectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStreamVectorResponse.Merge(m, src)
}
func (m *CreateStreamVectorResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStreamVectorResponse.Size(m)
}
func (m *CreateStreamVectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStreamVectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStreamVectorResponse proto.InternalMessageInfo

func (m *CreateStreamVectorResponse) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type Query struct {
	Namespace            string    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Points               []float32 `protobuf:"fixed32,2,rep,packed,name=points,proto3" json:"points,omitempty"`
	Neighbors            uint32    `protobuf:"varint,3,opt,name=neighbors,proto3" json:"neighbors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{7}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Query) GetPoints() []float32 {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *Query) GetNeighbors() uint32 {
	if m != nil {
		return m.Neighbors
	}
	return 0
}

type QueryRequest struct {
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{8}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type QueryResult struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance             float32  `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{9}
}

func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (m *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(m, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryResult) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type QueryResponse struct {
	Results              []*QueryResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{10}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type SizeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeRequest) Reset()         { *m = SizeRequest{} }
func (m *SizeRequest) String() string { return proto.CompactTextString(m) }
func (*SizeRequest) ProtoMessage()    {}
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{11}
}

func (m *SizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeRequest.Unmarshal(m, b)
}
func (m *SizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeRequest.Marshal(b, m, deterministic)
}
func (m *SizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeRequest.Merge(m, src)
}
func (m *SizeRequest) XXX_Size() int {
	return xxx_messageInfo_SizeRequest.Size(m)
}
func (m *SizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeRequest proto.InternalMessageInfo

type SizeResponse struct {
	Size                 uint32   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeResponse) Reset()         { *m = SizeResponse{} }
func (m *SizeResponse) String() string { return proto.CompactTextString(m) }
func (*SizeResponse) ProtoMessage()    {}
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{12}
}

func (m *SizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeResponse.Unmarshal(m, b)
}
func (m *SizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeResponse.Marshal(b, m, deterministic)
}
func (m *SizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeResponse.Merge(m, src)
}
func (m *SizeResponse) XXX_Size() int {
	return xxx_messageInfo_SizeResponse.Size(m)
}
func (m *SizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SizeResponse proto.InternalMessageInfo

func (m *SizeResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type AddEndpointRequest struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEndpointRequest) Reset()         { *m = AddEndpointRequest{} }
func (m *AddEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*AddEndpointRequest) ProtoMessage()    {}
func (*AddEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{13}
}

func (m *AddEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEndpointRequest.Unmarshal(m, b)
}
func (m *AddEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEndpointRequest.Marshal(b, m, deterministic)
}
func (m *AddEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEndpointRequest.Merge(m, src)
}
func (m *AddEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_AddEndpointRequest.Size(m)
}
func (m *AddEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEndpointRequest proto.InternalMessageInfo

func (m *AddEndpointRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type AddEndpointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEndpointResponse) Reset()         { *m = AddEndpointResponse{} }
func (m *AddEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*AddEndpointResponse) ProtoMessage()    {}
func (*AddEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{14}
}

func (m *AddEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEndpointResponse.Unmarshal(m, b)
}
func (m *AddEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEndpointResponse.Marshal(b, m, deterministic)
}
func (m *AddEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEndpointResponse.Merge(m, src)
}
func (m *AddEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_AddEndpointResponse.Size(m)
}
func (m *AddEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddEndpointResponse proto.InternalMessageInfo

type RemoveEndpointRequest struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEndpointRequest) Reset()         { *m = RemoveEndpointRequest{} }
func (m *RemoveEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveEndpointRequest) ProtoMessage()    {}
func (*RemoveEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{15}
}

func (m *RemoveEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEndpointRequest.Unmarshal(m, b)
}
func (m *RemoveEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEndpointRequest.Marshal(b, m, deterministic)
}
func (m *RemoveEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEndpointRequest.Merge(m, src)
}
func (m *RemoveEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveEndpointRequest.Size(m)
}
func (m *RemoveEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEndpointRequest proto.InternalMessageInfo

func (m *RemoveEndpointRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type RemoveEndpointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEndpointResponse) Reset()         { *m = RemoveEndpointResponse{} }
func (m *RemoveEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveEndpointResponse) ProtoMessage()    {}
func (*RemoveEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f49d9d6f0322bd5, []int{16}
}

func (m *RemoveEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEndpointResponse.Unmarshal(m, b)
}
func (m *RemoveEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEndpointResponse.Marshal(b, m, deterministic)
}
func (m *RemoveEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEndpointResponse.Merge(m, src)
}
func (m *RemoveEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveEndpointResponse.Size(m)
}
func (m *RemoveEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEndpointResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vector)(nil), "knn.Vector")
	proto.RegisterType((*CreateSingleVectorRequest)(nil), "knn.CreateSingleVectorRequest")
	proto.RegisterType((*CreateSingleVectorResponse)(nil), "knn.CreateSingleVectorResponse")
	proto.RegisterType((*CreateMultipleVectorRequest)(nil), "knn.CreateMultipleVectorRequest")
	proto.RegisterType((*CreateMultipleVectorResponse)(nil), "knn.CreateMultipleVectorResponse")
	proto.RegisterType((*CreateStreamVectorRequest)(nil), "knn.CreateStreamVectorRequest")
	proto.RegisterType((*CreateStreamVectorResponse)(nil), "knn.CreateStreamVectorResponse")
	proto.RegisterType((*Query)(nil), "knn.Query")
	proto.RegisterType((*QueryRequest)(nil), "knn.QueryRequest")
	proto.RegisterType((*QueryResult)(nil), "knn.QueryResult")
	proto.RegisterType((*QueryResponse)(nil), "knn.QueryResponse")
	proto.RegisterType((*SizeRequest)(nil), "knn.SizeRequest")
	proto.RegisterType((*SizeResponse)(nil), "knn.SizeResponse")
	proto.RegisterType((*AddEndpointRequest)(nil), "knn.AddEndpointRequest")
	proto.RegisterType((*AddEndpointResponse)(nil), "knn.AddEndpointResponse")
	proto.RegisterType((*RemoveEndpointRequest)(nil), "knn.RemoveEndpointRequest")
	proto.RegisterType((*RemoveEndpointResponse)(nil), "knn.RemoveEndpointResponse")
}

func init() { proto.RegisterFile("knn.proto", fileDescriptor_6f49d9d6f0322bd5) }

var fileDescriptor_6f49d9d6f0322bd5 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x51, 0x6f, 0xd3, 0x40,
	0x0c, 0x5e, 0x12, 0xda, 0xae, 0xee, 0x3a, 0xd1, 0x83, 0x8d, 0x90, 0x4d, 0x10, 0x0e, 0x21, 0x55,
	0x3c, 0x4c, 0xa5, 0x43, 0x48, 0x88, 0x17, 0x56, 0x40, 0x3c, 0x4c, 0x54, 0x22, 0x95, 0x40, 0x80,
	0x78, 0x48, 0x1b, 0xab, 0x8b, 0xda, 0x5e, 0xb2, 0xcb, 0xb5, 0x12, 0x7b, 0xe6, 0xa7, 0xf0, 0x43,
	0x51, 0xee, 0x2e, 0x69, 0xd2, 0x66, 0x9b, 0xe0, 0x2d, 0x3e, 0xdb, 0x9f, 0x3f, 0xfb, 0xb3, 0x03,
	0xcd, 0x19, 0x63, 0x27, 0x31, 0x8f, 0x44, 0x44, 0xac, 0x19, 0x63, 0x74, 0x08, 0xf5, 0x2f, 0x38,
	0x11, 0x11, 0x27, 0xfb, 0x60, 0x86, 0x81, 0x6d, 0xb8, 0x46, 0xb7, 0xe9, 0x99, 0x61, 0x40, 0x0e,
	0xa1, 0x1e, 0x47, 0x21, 0x13, 0x89, 0x6d, 0xba, 0x56, 0xd7, 0xf4, 0xb4, 0x45, 0x8e, 0xa1, 0xc9,
	0xfc, 0x05, 0x26, 0xb1, 0x3f, 0x41, 0xdb, 0x92, 0xe1, 0xeb, 0x07, 0xfa, 0x16, 0x1e, 0xbe, 0xe3,
	0xe8, 0x0b, 0x1c, 0x85, 0x6c, 0x3a, 0x47, 0x85, 0xed, 0xe1, 0xe5, 0x12, 0x13, 0x41, 0x9e, 0x42,
	0x7d, 0x25, 0x1f, 0x64, 0x99, 0x56, 0xbf, 0x75, 0x92, 0xb2, 0xd1, 0x31, 0xda, 0x45, 0x5f, 0x82,
	0x53, 0x85, 0x90, 0xc4, 0x11, 0x4b, 0x30, 0x65, 0xc5, 0x31, 0x59, 0xce, 0x85, 0x84, 0x68, 0x7b,
	0xda, 0xa2, 0xef, 0xe1, 0x48, 0x65, 0x7d, 0x5a, 0xce, 0x45, 0x18, 0x6f, 0x56, 0x7e, 0x06, 0x0d,
	0x05, 0x9f, 0xd8, 0x86, 0x6b, 0x6d, 0x96, 0xce, 0x7c, 0xf4, 0x15, 0x1c, 0x57, 0xa3, 0xdc, 0x52,
	0x7d, 0x90, 0x77, 0x2d, 0x38, 0xfa, 0x8b, 0xff, 0xaa, 0xbd, 0xee, 0xbb, 0x84, 0x71, 0x4b, 0xe5,
	0x1f, 0x50, 0xfb, 0xbc, 0x44, 0xfe, 0xab, 0x2c, 0x8b, 0xb1, 0x21, 0xcb, 0x8d, 0x62, 0x62, 0x38,
	0xbd, 0x18, 0xa7, 0xec, 0x2c, 0x89, 0xbc, 0x7e, 0xa0, 0x3d, 0xd8, 0x93, 0xe0, 0x59, 0x27, 0x2e,
	0xd4, 0x2e, 0x53, 0x5b, 0xcb, 0x07, 0xb2, 0x0f, 0x15, 0xa1, 0x1c, 0xf4, 0x35, 0xb4, 0x74, 0x46,
	0xca, 0x6e, 0x6b, 0xa7, 0x1c, 0xd8, 0x0d, 0xc2, 0x44, 0xf8, 0x6c, 0x82, 0xb6, 0xe9, 0x1a, 0x5d,
	0xd3, 0xcb, 0x6d, 0xfa, 0x06, 0xda, 0x59, 0xaa, 0x6a, 0xf9, 0x39, 0x34, 0x54, 0x93, 0xd9, 0xdc,
	0xee, 0x16, 0xea, 0x49, 0x87, 0x97, 0x05, 0xd0, 0x36, 0xb4, 0x46, 0xe1, 0x15, 0x6a, 0xa2, 0x94,
	0xc2, 0x9e, 0x32, 0x35, 0x14, 0x81, 0x3b, 0x49, 0x78, 0x85, 0x7a, 0x76, 0xf2, 0x9b, 0xf6, 0x80,
	0x9c, 0x05, 0xc1, 0x07, 0x16, 0xc8, 0x51, 0x64, 0x2d, 0x3a, 0xb0, 0x8b, 0xfa, 0x49, 0xf3, 0xce,
	0x6d, 0x7a, 0x00, 0xf7, 0x4a, 0x19, 0x0a, 0x9c, 0x9e, 0xc2, 0x81, 0x87, 0x8b, 0x68, 0x85, 0xff,
	0x82, 0x65, 0xc3, 0xe1, 0x66, 0x92, 0x82, 0xeb, 0xff, 0xb6, 0x00, 0xce, 0x87, 0xc3, 0x11, 0xf2,
	0x55, 0x38, 0x41, 0xf2, 0x15, 0xc8, 0xf6, 0x39, 0x90, 0x47, 0x72, 0x14, 0xd7, 0x5e, 0x9a, 0xf3,
	0xf8, 0x5a, 0xbf, 0x26, 0xbd, 0x43, 0x7e, 0xc2, 0xfd, 0xaa, 0x5d, 0x27, 0x6e, 0x21, 0xb5, 0xf2,
	0x98, 0x9c, 0x27, 0x37, 0x44, 0xe4, 0xf0, 0x2f, 0xa0, 0x3e, 0x42, 0x9f, 0x4f, 0x2e, 0x48, 0xa7,
	0x28, 0x9b, 0x42, 0x20, 0x25, 0x25, 0xb3, 0x94, 0x1e, 0x34, 0x3e, 0xa2, 0x48, 0x85, 0x23, 0x4a,
	0xea, 0x82, 0xa4, 0x4e, 0xa7, 0xf0, 0x92, 0x67, 0x7c, 0xcb, 0x87, 0x53, 0xb8, 0x99, 0xf2, 0x70,
	0xb6, 0x0f, 0xb2, 0x3c, 0x9c, 0x8a, 0x63, 0xa3, 0x3b, 0x5d, 0xa3, 0xff, 0xc7, 0x80, 0xce, 0xd9,
	0x74, 0xca, 0x71, 0xea, 0x8b, 0x88, 0x67, 0x6a, 0x0c, 0xa0, 0x55, 0x58, 0x01, 0xf2, 0x40, 0x22,
	0x6d, 0xaf, 0x91, 0x63, 0x6f, 0x3b, 0x72, 0xd2, 0xe7, 0xb0, 0x5f, 0x96, 0x9e, 0x38, 0x32, 0xba,
	0x72, 0x89, 0x9c, 0xa3, 0x4a, 0x5f, 0x06, 0x36, 0x68, 0x7c, 0xaf, 0xcd, 0x18, 0x8b, 0xc7, 0xe3,
	0xba, 0xfc, 0xa9, 0x9f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x49, 0x87, 0x6b, 0xe1, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KNNServiceClient is the client API for KNNService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KNNServiceClient interface {
	// Unary
	CreateSingleVector(ctx context.Context, in *CreateSingleVectorRequest, opts ...grpc.CallOption) (*CreateSingleVectorResponse, error)
	CreateMultipleVector(ctx context.Context, in *CreateMultipleVectorRequest, opts ...grpc.CallOption) (*CreateMultipleVectorResponse, error)
	Search(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	GetSize(ctx context.Context, in *SizeRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	// Client Streaming
	CreateStreamVector(ctx context.Context, opts ...grpc.CallOption) (KNNService_CreateStreamVectorClient, error)
}

type kNNServiceClient struct {
	cc *grpc.ClientConn
}

func NewKNNServiceClient(cc *grpc.ClientConn) KNNServiceClient {
	return &kNNServiceClient{cc}
}

func (c *kNNServiceClient) CreateSingleVector(ctx context.Context, in *CreateSingleVectorRequest, opts ...grpc.CallOption) (*CreateSingleVectorResponse, error) {
	out := new(CreateSingleVectorResponse)
	err := c.cc.Invoke(ctx, "/knn.KNNService/CreateSingleVector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kNNServiceClient) CreateMultipleVector(ctx context.Context, in *CreateMultipleVectorRequest, opts ...grpc.CallOption) (*CreateMultipleVectorResponse, error) {
	out := new(CreateMultipleVectorResponse)
	err := c.cc.Invoke(ctx, "/knn.KNNService/CreateMultipleVector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kNNServiceClient) Search(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/knn.KNNService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kNNServiceClient) GetSize(ctx context.Context, in *SizeRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	out := new(SizeResponse)
	err := c.cc.Invoke(ctx, "/knn.KNNService/GetSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kNNServiceClient) CreateStreamVector(ctx context.Context, opts ...grpc.CallOption) (KNNService_CreateStreamVectorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KNNService_serviceDesc.Streams[0], "/knn.KNNService/CreateStreamVector", opts...)
	if err != nil {
		return nil, err
	}
	x := &kNNServiceCreateStreamVectorClient{stream}
	return x, nil
}

type KNNService_CreateStreamVectorClient interface {
	Send(*CreateStreamVectorRequest) error
	CloseAndRecv() (*CreateStreamVectorResponse, error)
	grpc.ClientStream
}

type kNNServiceCreateStreamVectorClient struct {
	grpc.ClientStream
}

func (x *kNNServiceCreateStreamVectorClient) Send(m *CreateStreamVectorRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kNNServiceCreateStreamVectorClient) CloseAndRecv() (*CreateStreamVectorResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CreateStreamVectorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KNNServiceServer is the server API for KNNService service.
type KNNServiceServer interface {
	// Unary
	CreateSingleVector(context.Context, *CreateSingleVectorRequest) (*CreateSingleVectorResponse, error)
	CreateMultipleVector(context.Context, *CreateMultipleVectorRequest) (*CreateMultipleVectorResponse, error)
	Search(context.Context, *QueryRequest) (*QueryResponse, error)
	GetSize(context.Context, *SizeRequest) (*SizeResponse, error)
	// Client Streaming
	CreateStreamVector(KNNService_CreateStreamVectorServer) error
}

// UnimplementedKNNServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKNNServiceServer struct {
}

func (*UnimplementedKNNServiceServer) CreateSingleVector(ctx context.Context, req *CreateSingleVectorRequest) (*CreateSingleVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSingleVector not implemented")
}
func (*UnimplementedKNNServiceServer) CreateMultipleVector(ctx context.Context, req *CreateMultipleVectorRequest) (*CreateMultipleVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMultipleVector not implemented")
}
func (*UnimplementedKNNServiceServer) Search(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedKNNServiceServer) GetSize(ctx context.Context, req *SizeRequest) (*SizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSize not implemented")
}
func (*UnimplementedKNNServiceServer) CreateStreamVector(srv KNNService_CreateStreamVectorServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateStreamVector not implemented")
}

func RegisterKNNServiceServer(s *grpc.Server, srv KNNServiceServer) {
	s.RegisterService(&_KNNService_serviceDesc, srv)
}

func _KNNService_CreateSingleVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSingleVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KNNServiceServer).CreateSingleVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knn.KNNService/CreateSingleVector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KNNServiceServer).CreateSingleVector(ctx, req.(*CreateSingleVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KNNService_CreateMultipleVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMultipleVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KNNServiceServer).CreateMultipleVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knn.KNNService/CreateMultipleVector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KNNServiceServer).CreateMultipleVector(ctx, req.(*CreateMultipleVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KNNService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KNNServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knn.KNNService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KNNServiceServer).Search(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KNNService_GetSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KNNServiceServer).GetSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knn.KNNService/GetSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KNNServiceServer).GetSize(ctx, req.(*SizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KNNService_CreateStreamVector_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KNNServiceServer).CreateStreamVector(&kNNServiceCreateStreamVectorServer{stream})
}

type KNNService_CreateStreamVectorServer interface {
	SendAndClose(*CreateStreamVectorResponse) error
	Recv() (*CreateStreamVectorRequest, error)
	grpc.ServerStream
}

type kNNServiceCreateStreamVectorServer struct {
	grpc.ServerStream
}

func (x *kNNServiceCreateStreamVectorServer) SendAndClose(m *CreateStreamVectorResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kNNServiceCreateStreamVectorServer) Recv() (*CreateStreamVectorRequest, error) {
	m := new(CreateStreamVectorRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _KNNService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "knn.KNNService",
	HandlerType: (*KNNServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSingleVector",
			Handler:    _KNNService_CreateSingleVector_Handler,
		},
		{
			MethodName: "CreateMultipleVector",
			Handler:    _KNNService_CreateMultipleVector_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _KNNService_Search_Handler,
		},
		{
			MethodName: "GetSize",
			Handler:    _KNNService_GetSize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStreamVector",
			Handler:       _KNNService_CreateStreamVector_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "knn.proto",
}

// AggregatorServiceClient is the client API for AggregatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AggregatorServiceClient interface {
	AddEndpoint(ctx context.Context, in *AddEndpointRequest, opts ...grpc.CallOption) (*AddEndpointResponse, error)
	RemoveEndpoint(ctx context.Context, in *RemoveEndpointRequest, opts ...grpc.CallOption) (*RemoveEndpointResponse, error)
}

type aggregatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewAggregatorServiceClient(cc *grpc.ClientConn) AggregatorServiceClient {
	return &aggregatorServiceClient{cc}
}

func (c *aggregatorServiceClient) AddEndpoint(ctx context.Context, in *AddEndpointRequest, opts ...grpc.CallOption) (*AddEndpointResponse, error) {
	out := new(AddEndpointResponse)
	err := c.cc.Invoke(ctx, "/knn.AggregatorService/AddEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorServiceClient) RemoveEndpoint(ctx context.Context, in *RemoveEndpointRequest, opts ...grpc.CallOption) (*RemoveEndpointResponse, error) {
	out := new(RemoveEndpointResponse)
	err := c.cc.Invoke(ctx, "/knn.AggregatorService/RemoveEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregatorServiceServer is the server API for AggregatorService service.
type AggregatorServiceServer interface {
	AddEndpoint(context.Context, *AddEndpointRequest) (*AddEndpointResponse, error)
	RemoveEndpoint(context.Context, *RemoveEndpointRequest) (*RemoveEndpointResponse, error)
}

// UnimplementedAggregatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAggregatorServiceServer struct {
}

func (*UnimplementedAggregatorServiceServer) AddEndpoint(ctx context.Context, req *AddEndpointRequest) (*AddEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEndpoint not implemented")
}
func (*UnimplementedAggregatorServiceServer) RemoveEndpoint(ctx context.Context, req *RemoveEndpointRequest) (*RemoveEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEndpoint not implemented")
}

func RegisterAggregatorServiceServer(s *grpc.Server, srv AggregatorServiceServer) {
	s.RegisterService(&_AggregatorService_serviceDesc, srv)
}

func _AggregatorService_AddEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServiceServer).AddEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knn.AggregatorService/AddEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServiceServer).AddEndpoint(ctx, req.(*AddEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregatorService_RemoveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServiceServer).RemoveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knn.AggregatorService/RemoveEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServiceServer).RemoveEndpoint(ctx, req.(*RemoveEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AggregatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "knn.AggregatorService",
	HandlerType: (*AggregatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEndpoint",
			Handler:    _AggregatorService_AddEndpoint_Handler,
		},
		{
			MethodName: "RemoveEndpoint",
			Handler:    _AggregatorService_RemoveEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knn.proto",
}
